select.pf-v5-c-form-control[multiple] {
  height: auto !important;
  min-height: 6rem;
  overflow: auto !important;
  border: 1px solid #ccc;
  padding: 0.25rem;
  box-shadow: none;
  background: white;
  appearance: listbox; /* Ensures native multi-select styling */
}
