document.addEventListener("DOMContentLoaded", function () {
    const openBtn = document.getElementById('openModalBtn');
    const modalBackdrop = document.getElementById('modalBackdrop');
    const modalBox = document.getElementById('modalBox');
    const closeBtn = document.getElementById('closeModalBtn');

    function showModal() {
        modalBackdrop.style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }

    function hideModal() {
        modalBackdrop.style.display = 'none';
        document.body.style.overflow = '';
    }

    openBtn?.addEventListener('click', showModal);
    closeBtn?.addEventListener('click', hideModal);

    // Click outside modal
    modalBackdrop.addEventListener('click', function (event) {
        if (!modalBox.contains(event.target)) {
            hideModal();
        }
    });

    // ESC to close
    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape') {
            hideModal();
        }
    });
});
