<!-- Trigger Button -->
<button id="openModalBtn" class="pf-v5-c-button pf-m-primary" style="margin: 2rem;">Show Modal</button>

<!-- Modal Backdrop -->
<div id="modalBackdrop" style="display: none; position: fixed; top: 0; left: 0; 
    width: 100%; height: 100%; background: rgba(0,0,0,0.5); 
    z-index: 9999; justify-content: center; align-items: center;">
  
  <!-- Modal Box -->
  <div id="modalBox" style="background: white; padding: 2rem; border-radius: 6px; 
      width: 90%; max-width: 500px; box-shadow: 0 0 10px rgba(0,0,0,0.3);">
    
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <h2>Modal title</h2>
      <button id="closeModalBtn" class="pf-v5-c-button pf-m-plain" aria-label="Close">
        <i class="fas fa-times"></i>
      </button>
    </div>

    <p style="margin-top: 1rem;">
      Static text describing modal purpose. Click outside this box or press "X" or Esc to close.
    </p>
  </div>
</div>



document.addEventListener("DOMContentLoaded", function () {
    const openBtn = document.getElementById('openModalBtn');
    const closeBtn = document.getElementById('closeModalBtn');
    const modalBackdrop = document.getElementById('modalBackdrop');
    const modalBox = document.getElementById('modalBox');

    function showModal() {
        modalBackdrop.style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }

    function hideModal() {
        modalBackdrop.style.display = 'none';
        document.body.style.overflow = '';
    }

    openBtn.addEventListener('click', showModal);
    closeBtn.addEventListener('click', hideModal);

    // Close if clicked outside the modal box
    modalBackdrop.addEventListener('click', function (event) {
        if (!modalBox.contains(event.target)) {
            hideModal();
        }
    });

    // Close with ESC key
    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape') {
            hideModal();
        }
    });
});
