
document.addEventListener("DOMContentLoaded", function () {
    const openBtn = document.getElementById('openModalBtn');
    const modalBackdrop = document.getElementById('modalBackdrop');
    const modalBox = document.getElementById('modalBox');
    const closeBtn = document.getElementById('closeModalBtn');

    function showModal() {
        modalBackdrop.style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }

    function hideModal() {
        modalBackdrop.style.display = 'none';
        document.body.style.overflow = '';
    }

    if (openBtn) openBtn.addEventListener('click', showModal);
    if (closeBtn) closeBtn.addEventListener('click', hideModal);

    // Close when clicking outside the modal box
    modalBackdrop.addEventListener('click', function (event) {
        if (!modalBox.contains(event.target)) {
            hideModal();
        }
    });

    // Close with ESC key
    document.addEventListener('keydown', function (event) {
        if (event.key === 'Escape') {
            hideModal();
        }
    });
});
